baseURL = 'https://fernandezvara.github.io/www.displasiafibrosa.es/'
languageCode = 'es-es'
title = 'Asociación de Displasia Fibrosa'

[params]
  description = "Asociación de Displasia Fibrosa - Ayudamos a afectados por DF y MAS"
  author = "Asociación de Displasia Fibrosa"
  logo = "/images/logo.svg"
  
[menu]
  [[menu.main]]
    name = "La Asociación"
    url = "/asociacion/"
    weight = 10
    
  [[menu.main]]
    name = "Quiénes somos"
    url = "/asociacion/quienes-somos/"
    parent = "La Asociación"
    weight = 11
    
  [[menu.main]]
    name = "Nuestros fines"
    url = "/asociacion/nuestros-fines/"
    parent = "La Asociación"
    weight = 12
    
  [[menu.main]]
    name = "Junta Directiva"
    url = "/asociacion/junta-directiva/"
    parent = "La Asociación"
    weight = 13
    
  [[menu.main]]
    name = "Comité Científico"
    url = "/asociacion/comite-cientifico/"
    parent = "La Asociación"
    weight = 14
    
  [[menu.main]]
    name = "Estatutos de la Asociación"
    url = "/asociacion/estatutos-de-la-asociacion/"
    parent = "La Asociación"
    weight = 15
    
  [[menu.main]]
    name = "Memoria de Actividades"
    url = "/asociacion/memoria-de-actividades/"
    parent = "La Asociación"
    weight = 16
    
  [[menu.main]]
    name = "Información Económica"
    url = "/asociacion/informacion-economica/"
    parent = "La Asociación"
    weight = 17
    
  [[menu.main]]
    name = "Colaboradores"
    url = "/asociacion/colaboradores/"
    parent = "La Asociación"
    weight = 18
    
  [[menu.main]]
    name = "Un regalo llamado Mateo"
    url = "/asociacion/un-regalo-llamado-mateo/"
    parent = "La Asociación"
    weight = 19

  [[menu.main]]
    name = "Otras Asociaciones"
    url = "/asociacion/otras-asociaciones/"
    parent = "La Asociación"
    weight = 31

  [[menu.main]]
    name = "La Enfermedad"
    url = "/enfermedad/"
    weight = 20
    
  [[menu.main]]
    name = "Preguntas Frecuentes"
    url = "/enfermedad/preguntas-frecuentes/"
    parent = "La Enfermedad"
    weight = 21
    
  [[menu.main]]
    name = "Displasia Fibrosa"
    url = "/enfermedad/displasia-fibrosa/"
    parent = "La Enfermedad"
    weight = 22
    
  [[menu.main]]
    name = "Síndrome McCune-Albright"
    url = "/enfermedad/sindrome-mccune-albright/"
    parent = "La Enfermedad"
    weight = 23
    
  [[menu.main]]
    name = "Guía Médica"
    url = "/enfermedad/guia-medica/"
    parent = "La Enfermedad"
    weight = 24
  
  [[menu.main]]
    name = "Guía Médica 2019 (v.o. en Inglés)"
    url = "/enfermedad/guia-medica-2019-vo/"
    parent = "La Enfermedad"
    weight = 26
        
  [[menu.main]]
    name = "Libro Blanco"
    url = "/enfermedad/libro-blanco/"
    parent = "La Enfermedad"
    weight = 27
    
  [[menu.main]]
    name = "Exención de responsabilidad"
    url = "/enfermedad/exencion-de-responsabilidad/"
    parent = "La Enfermedad"
    weight = 28
    
  [[menu.main]]
    name = "Eventos"
    url = "/eventos/"
    weight = 29
    
  [[menu.main]]
    name = "Noticias"
    url = "/eventos/noticias/"
    parent = "Eventos"
    weight = 30
  
  [[menu.main]]
    name = "Congreso Florencia 2019"
    url = "/recursos/congresos/florencia-2019/"
    parent = "Eventos"
    weight = 33
    
  [[menu.main]]
    name = "I Congreso Nacional Burgos 2019"
    url = "/recursos/congresos/burgos-2019/"
    parent = "Eventos"
    weight = 34
    
  [[menu.main]]
    name = "II Congreso Nacional 2021"
    url = "/recursos/congresos/2021/"
    parent = "Eventos"
    weight = 35
    
  [[menu.main]]
    name = "III Congreso Nacional 2022"
    url = "/recursos/congresos/2022/"
    parent = "Eventos"
    weight = 36
    
  [[menu.main]]
    name = "IV Congreso Nacional 2023"
    url = "/recursos/congresos/2023/"
    parent = "Eventos"
    weight = 37
    
  [[menu.main]]
    name = "Recursos"
    url = "/recursos/"
    weight = 32

  [[menu.main]]
    name = "Prensa escrita"
    url = "/recursos/prensa-escrita"
    parent = "Recursos"
    weight = 39

  [[menu.main]]
    name = "Video Displasia Fibrosa"
    url = "/recursos/video-displasia-fibrosa"
    parent = "Recursos"
    weight = 40

  [[menu.main]]
    name = "Vídeos en medios"
    url = "/recursos/videos"
    parent = "Recursos"
    weight = 41

  [[menu.main]]
    name = "Vídeo campañas ADF"
    url = "/recursos/videos-adf"
    parent = "Recursos"
    weight = 42

  [[menu.main]]
    name = "Tríptico ADF"
    url = "/recursos/triptico"
    parent = "Recursos"
    weight = 43

  [[menu.main]]
    name = "Información sobre discapacidad"
    url = "/recursos/informacion-discapacidad"
    parent = "Recursos"
    weight = 44
    
  [[menu.main]]
    name = "Contacto"
    url = "/contacto/"
    weight = 38

[pagination]
  pagerSize = 6
  path = 'page'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  writeStats = true

[taxonomies]
  category = "categories"

[permalinks]
  [permalinks.term]
    categories = "/noticias/categoria/:slug/"
