baseURL = 'https://www.displasiafibrosa.es'
languageCode = 'es-es'
title = 'ADF - Asociaci贸n de Displasia Fibrosa'

[params]
  description = "Asociaci贸n de Displasia Fibrosa - Ayudamos a afectados por DF y MAS"
  author = "Asociaci贸n de Displasia Fibrosa"
  logo = "/images/logo.svg"
  
[menu]
  [[menu.main]]
    name = "La Asociaci贸n"
    url = "/asociacion/"
    weight = 10
    
  [[menu.main]]
    name = "La Enfermedad"
    url = "/enfermedad/"
    weight = 20
    
  [[menu.main]]
    name = "Recursos"
    url = "/recursos/"
    weight = 30
    
  [[menu.main]]
    name = "Noticias"
    url = "/noticias/"
    weight = 40
    
  [[menu.main]]
    name = "Contacto"
    url = "/contacto/"
    weight = 50

[pagination]
  pagerSize = 6
  path = 'page'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
